services:
  md2video:
    build: .
    volumes:
      - ${CONTENT_DIR}:/app/content
      - ${SCRIPT_DIR}:/app/video_scripts
      - ${OUTPUT_DIR}:/app/video_output
      - ./.env:/app/.env
    env_file:
      - .env

  test:
    build: .
    command: pytest --cov=src --cov-report=term-missing
    volumes:
      - .:/app
